### ISSUE TITLE
Dependency on pagerduty-sdk causes bundler to fail

### ISSUE THREAD

**Issue by harlanbarnes** [PagerDuty/lita-pagerduty#2]
Hi Eric,

I know this isn't your issue per se. But I was hoping you might know more about it.

I recently started using Lita and lita-pagerduty specifically. I wrote a Chef cookbook for it and had to do a workaround because of the pagerduty-sdk rubygem has a dependency on "active_support" instead of "activesupport":

https://github.com/litaio/chef-lita#todo

The pagerduty-sdk rubygem was patched in Github in February but not yet released:

https://github.com/kryptek/pagerduty-sdk/pull/2
http://rubygems.org/gems/pagerduty-sdk/versions/1.0.5

Is that gem the official rubygem of PagerDuty? (I don't think is nor do I think one exists, but just checking.)

If not, do you happen to know the maintainer of rubygem-sdk and could coax him into releasing a new gem?

If not, would you entertain a PR switching lita-pagerduty to another PagerDuty rubygem that seems like it it's more actively developed? (This perhaps? http://rubygems.org/gems/pagerduty)

Thanks for developing lita-pagerduty!

Harlan

**Comment by chrisgagne** [comment]
@kryptek @rohitpaulk @harlanbarnes If you all agree that @kryptek's commit solved the issue, there's a $100 bounty available to him on https://www.bountysource.com/issues/3312124-dependency-on-pagerduty-sdk-causes-bundler-to-fail

**Comment by kryptek** [comment]
Hey, pretty cool. I'd love to receive the bounty!

I'd done some work on a complete rewrite of my pagerduty-sdk gem around mid-last year but work at AWS has been so busy that I kind of just dropped development on it. The new version even has test cases for all the API methods. I guess I never really gathered a sense of how useful the gem was to people. I used Pagerduty at my last place of employment and that was why I'd created it in the first place. If you guys are really interested in further work on it, I'd love to share.

**Comment by rohitpaulk** [comment]
Yes, @kryptek's issue did solve the issue :)
