### ISSUE TITLE
PagerDuty V2 api does not work

### ISSUE THREAD

**Issue by kendrickm** [PagerDuty/lita-pagerduty#24]
The V2 api for pager duty integrations don't work

**Comment by northrup** [comment]
With the announcement of the v1 API going away, will there be any traction on this issue?

**Comment by pwyliu** [comment]
Since the V1 API is going away on October 19th, it would be nice to have a comment about this one way or the other.

**Comment by tehsven** [comment]
Looks like this was fixed: https://github.com/PagerDuty/lita-pagerduty/pull/27

**Comment by tristaneuan** [comment]
Yep! This has been fixed as of version `1.0.0`
