### ISSUE TITLE
Add "who's oncall" functionality

### ISSUE THREAD

**Issue by schisamo** [PagerDuty/lita-pagerduty#4]
We here at [Chef](https://www.chef.io/) are currently migrating from Hubot to Lita and need to ensure users can ask the bot for the current 'oncall' schedule. I noticed @harlanbarnes [took a stab at adding this functionality back in August](https://github.com/PagerDuty/lita-pagerduty/issues/3). We (Chef) would love to help out in this effort but I want to ensure y'all don't have unpushed work started we might be duplicating.

**Comment by esigler** [comment]
@schisamo Go right ahead!  I cleaned up a lot of the internals a few days ago but haven't done any functionality enhancements yet.

**Comment by bhouse** [comment]
:+1:

**Comment by esigler** [comment]
@davidcornu 's commits have been added and released as lita-pagerduty 0.1.0.

**Comment by schisamo** [comment]
Awesome work @davidcornu!

**Comment by johntdyer** [comment]
Went ahead and sent a PR ( #6 ) to update readme with new feature.  @davidcornu  thanks for this awesome PR !

**Comment by davidcornu** [comment]
No problem. Glad it was merged
