### ISSUE TITLE
Broken - pager identify

### ISSUE THREAD

**Issue by Ginja** [PagerDuty/lita-pagerduty#7]
Hi,

Great plugin. But I'm unable to use the `pager identify <emailaddress>` functionality (there's no response in Slack, and nothing in the logs). From my debugging, it looks like the route isn't matching (simply added toasts inside the `def identify(response)` function, and watched logs).

I checked on http://rubular.com if your EMAIL_PATTERN regex would match what I'm specifying and it does, so it's not anything to do with that.

Do you have any thoughts on why this is happening?

**Comment by esigler** [comment]
I wonder if this is another case of auto-magic formatting by Slack (similar to URL formatting - https://github.com/kenjij/lita-slack/pull/35)?

**Comment by Ginja** [comment]
Just updated the lita-slack adapter to 1.5, and happy to report that pager identify now works. Thanks for the info!
